### ISSUE TITLE
向大家道歉。

### ISSUE THREAD

**Issue by ghost** [woshixuwenqi/zhengju#1]
成人真的不容易，还要工作，还要养着家。希望你也能理解。你这个东西一放。我可能就要和工作拜拜了。我是无所谓。但是我的家人呢？怼了你，给你心情不好了，确实不应该。

自己遭遇多大的变故都不能让别人也跟着我一起心情不好。这个确实是我错。我道歉。还请你高抬贵手，不饶我，就当是饶我的家人吧。说实话，我一个大男人，哈哈，要不是为了家人也不会这么低三下四的求人的。况且真的是我的错，我的不对。

言语过激确实是我不对。还望小友海涵。烦请删了这个仓库，绕我一个饭碗。也是我一家人的饭碗。我家确实只有我在工作。

**Comment by Anankke** [comment]
丢了就丢了，你不值得这饭碗，xswl。

**Comment by ghost** [comment]
不知道你多大。有没有体会到生活的不容易。这么做确实太过分了。得饶人处且饶人，别人话都这么说了，请你放个手而已。

**Comment by ghost** [comment]
你也是河北人，应该也是一个汉子。别人都这样了，你还要逼死我吗？我都说了，像你诚挚的道歉，而且家中就我一个人有工作，大家都是人，希望你动一点点的恻隐之心，劳烦一下了。

**Comment by woshixuwenqi** [comment]
大兄弟，哥也知道生活不容易，谁能知道自己会收到几百封两个沙雕在吵架的邮件呢。
你道歉的对象错了，你的诚意我也看不到。
先去那边给400个watchers道歉让我康康

**Comment by ghost** [comment]
没问题道歉是应该的。

**Comment by ghost** [comment]
事情发生的时候，头脑一热什么都不会想。发生之后知道不对。我们已经互相道歉了。等一下我去那边的仓库说

**Comment by woshixuwenqi** [comment]
还有DanmakuFlameMaster的开发者。

**Comment by ghost** [comment]
道歉了。还有对你也道歉。污染了你的邮箱。

**Comment by woshixuwenqi** [comment]
奈斯，哥也是讲义气的。这个事情之后，咱就是兄弟。哥呢也讲道义，哥保证不会有进一步操作了，就此别过。

**Comment by ghost** [comment]
兄弟，劳烦把这个库删掉吧。卖源码那件事我和leurn也说了。和女友分手，报了一个挽回机构，智商税要一万4。我的钱都给家里了。一时都拿不到钱，就想各种办法。卖代码，卖游戏账号的。

**Comment by ghost** [comment]
这个库，领导都会看到的。饭碗没了我没什么问题，关键我还有家人呢，不能让我母亲因为我脑抽而买单。我实在是对不起她

**Comment by ghost** [comment]
人，还是不能做一些违反规则的事。有个词语可能很偏激，但有一点意思，红颜祸水，哈哈。自己脑残的时候，为了个女的什么都干。到头来吃亏的是自己。她都不知道你干了什么，可能都成了别人的人了，分开的那段时间真的很难受，各种倒卖自己能卖的东西。有一个叫恋一生的挽回机构，以为可以教我如何挽回，报了名交了钱却没什么结果，分开就是分开了，都有各自的原因，是我看不开罢了。为了她还做了这种事情，不值得。母亲什么的，最对不起了。希望她可以好起来，医生都说了，是良性的，会好的，希望不用我再凑什么医费了，也不希望你可怜我什么，一个男人顶天立地，为了母亲来捧起饭碗，我自豪。为了爱人，做出一些出格的事，我活该，但我能做的都做的，不能做的也做了，她不回来，我也不后悔了，我尽力了。只是对不起我的母亲了。
